#!/bin/bash

rm -rf target
mkdir target
nosetests -v\
	--with-xunit --xunit-file=target/nosetests.xml\
	--with-coverage --cover-xml --cover-xml-file=target/coverage.xml\
	--cover-erase --cover-tests --cover-inclusive --cover-branches\
	--with-doctest

